<?php

namespace backend\controllers;

use MongoDB\BSON\Timestamp;
use Yii;
use backend\models\Apple;
use backend\models\AppleSearch;
use yii\base\ExitException;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use function Sodium\compare;

/**
 * AppleController implements the CRUD actions for Apple model.
 */
class AppleController extends Controller
{

    public $arrayAppleColor =  ["green", "red", "yellow"];
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * Lists all Apple models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AppleSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Apple model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     * @throws \Throwable
     */
    public function actionCreate()
    {
        $countApple = random_int(1, 10);
        for ($i = 0; $i <= $countApple; $i++) {
            $model = new Apple();
            $model->color = $this->arrayAppleColor[random_int(0, 2)];
            $model->status_id = Apple::APPLE_ON_TREE;
            $model->insert();
        }
        return $this->redirect('index');
    }

    /**
     * @param integer $id
     * @return mixed
     *
     */
    public function actionFall($id)
    {
        $model = Apple::findOne($id);
        $model->status_id = Apple::APPLE_ON_GROUND;
        $model->touch("updated_at");
        $model->point_no_return = ($model->updated_at) + 18000;
        $model->update();
        return $this->redirect('index');
    }

    /**
     * @param integer $id
     * @return mixed
     *
     */
    public function actionEat($id)
    {
        $model = Apple::findOne($id);
        $request = Yii::$app->request;
//        $diffTime = Timestamp::class;
//        $diffTime->too
        if ($request->isAjax) {
//            if ($model->status_id == 1) {
//                return 'Съесть не получится - не дереве';
//            } else if ($model->status_id == 3) {
//                return 'Съесть не поулчится  - сгнило ';
//            } else {

                $countEat = $request->queryParams;
                $howMuchLeft = $model->how_much_left;
                $model->how_much_left = (($howMuchLeft - $countEat['eat'] / 100) <= 0) ? $this->actionDelete($id) : $howMuchLeft - $countEat['eat'] / 100;
                $model->save();
                return $this->redirect('index');
            //}
        }
        return $this->redirect('index');
    }

    /**
     * Deletes an existing Apple model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Apple model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Apple the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Apple::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionView($id=9)
    {
        $model = Apple::findOne($id);

        $time = time();

        return $this->render('view', [
            'timeNow' => $time,
            'model' => $model,
        ]);
    }

}
