<?php

namespace yii\behaviors;

use yii\base\Behavior;

class MyBehavior extends Behavior
{
    public function events()
    {
        return parent::events(); // TODO: Change the autogenerated stub
    }

    public function

}